#!/bin/bash
declare -a args
if (($# == 0)); then # or ${#args[@]}
    args=(`docker inspect -f '{{.NetworkSettings.IPAddress}}' blockchain-mail-node-0`)
else
    args=($@)
fi
go run main.go "${args[@]}"
